blas1 kokkos: add
kokkos/stdBLAS pull request #159
Opened 2022-04-08 06:36 UTC by fnrizzi

2022-04-10 00:36 UTC, mhoemmen requested changes

2022-04-10 00:36 UTC, mhoemmen commented on tpl-implementations/include/experimental/__p1673_bits/kokkos-kernels/mdspan_to_view_mapper_kk.hpp
> +  && is_complex_v<typename MDSpan::element_type>,
This is incorrect for `const` and/or `volatile`-qualified `element_type`.  Please see my comments on PR #162.

2022-04-14 09:34 UTC, fnrizzi commented
@mhoemmen this is ready IMO

2022-04-15 04:34 UTC, mhoemmen approved these changes
Looks great!  Thanks for the contribution and for your responses to feedback!

It looks like there's a merge conflict, so I can't merge this one, alas.

2022-04-15 07:51 UTC, fnrizzi commented
> Looks great! Thanks for the contribution and for your responses to feedback!
> 
> It looks like there's a merge conflict, so I can't merge this one, alas.

conflict fixed via #172

2022-04-15 14:36 UTC, merged