scale: kokkos impl
kokkos/stdBLAS pull request #161
Opened 2022-04-08 06:52 UTC by fnrizzi

2022-04-10 01:01 UTC, mhoemmen requested changes

2022-04-10 01:01 UTC, mhoemmen commented on tpl-implementations/include/experimental/__p1673_bits/kokkos-kernels/blas1_scale_kk.hpp
> +  std::cout << "scale: kokkos impl\n";
Please see my comment on e.g., PR #160 about encapsulating logging.  This is not required but would be a good idea (I think : - ) ).  Thanks!

2022-04-10 01:01 UTC, mhoemmen commented on tpl-implementations/include/experimental/__p1673_bits/kokkos-kernels/mdspan_to_view_mapper_kk.hpp
> +  && !is_complex_v<typename MDSpan::element_type>,
Please see my comments on PR #162.  This won't work for e.g., `mdspan<const std::complex<T>, ...>`.

2022-04-14 09:57 UTC, fnrizzi commented
@mhoemmen this is ready IMO

2022-04-15 04:36 UTC, mhoemmen approved these changes
Looks great!  Thanks for the contribution and for your responses to feedback!

It looks like there's a merge conflict, alas.

2022-04-15 04:36 UTC, mhoemmen commented on tpl-implementations/include/experimental/__p1673_bits/kokkos-kernels/blas1_scale_kk.hpp
> +requires (sizeof...(ext) <= 2)
This is a perfectly fine way to express the constraint.  You could also add a `requires` clause after the function's parameters, and do `requires(obj.rank() <= 2)`.

2022-04-15 07:52 UTC, fnrizzi commented
@mhoemmen conflict fixed via #172

2022-04-15 14:35 UTC, mhoemmen commented on tpl-implementations/include/experimental/__p1673_bits/kokkos-kernels/blas1_scale_kk.hpp
> +requires (sizeof...(ext) <= 2)
Just to clarify: Either way is fine with me : - )

2022-04-15 14:35 UTC, mhoemmen approved these changes

2022-04-15 14:35 UTC, merged