`trianguler_matrix_vector_product`: kokkos impl
kokkos/stdBLAS pull request #165
Opened 2022-04-08 07:51 UTC by fnrizzi

#162   is a prerequisite for this, I can rebase once that is merged

2022-04-11 00:57 UTC, mhoemmen requested changes

2022-04-11 00:57 UTC, mhoemmen commented on tpl-implementations/include/experimental/__p1673_bits/kokkos-kernels/blas2_triangular_mat_vec_product.hpp
> +  // constraints
Please see comments on other PRs about Constraints vs. Mandates; thanks!

2022-04-11 00:57 UTC, mhoemmen commented on tpl-implementations/include/experimental/__p1673_bits/kokkos-kernels/blas2_triangular_mat_vec_product.hpp
> +  std::cout << "overwriting_triangular_matrix_vector_product_lower: kokkos impl\n";
Please see comments on my other PRs about logging encapsulation; thanks!

2022-04-11 00:57 UTC, mhoemmen commented on tpl-implementations/include/experimental/__p1673_bits/kokkos-kernels/mdspan_to_view_mapper_kk.hpp
> +  && !is_complex_v<typename MDSpan::element_type>,
Please see my comments on PR #162.  That's the only thing I think _needs_ to be fixed in this PR.  Thanks!

2022-04-22 15:46 UTC, mhoemmen approved these changes

2022-04-25 05:31 UTC, fnrizzi commented on tpl-implementations/include/experimental/__p1673_bits/kokkos-kernels/blas2_triangular_mat_vec_product.hpp
> +    Kokkos::parallel_for(Kokkos::RangePolicy(ex, 0, A_view.extent(0)),
not that I see! there is only `trmm` https://github.com/kokkos/kokkos-kernels/wiki/BLAS

2022-04-25 21:19 UTC, merged